version: '3'

services:

  www:
    image: tmvdl/challenges:calendario
    hostname: www
    build: './src/www'
    restart: always
    volumes:
      - './src/www/:/app'
    ports:
      - '80:80'

  api_tasks_create:
    hostname: 'api_tasks_create'
    build: './src/taskscreate/'
    restart: always
    volumes:
      - './src/taskscreate/:/project'
      - './src/main/:/commons'
      - './data:/data'

  api_tasks_list:
    hostname: 'api_tasks_list'
    build: './src/taskslist/'
    restart: always
    volumes:
      - './src/taskslist/:/project'
      - './src/main/:/commons'
      - './data:/data'

  api_tasks_get:
    hostname: 'api_tasks_get'
    build: './src/tasksget/'
    restart: always
    volumes:
      - './src/tasksget/:/project'
      - './src/main/:/commons'
      - './data:/data'

  # api_tasks_update:
  #   hostname: 'api_tasks_update'
  #   build: './src/tasksupdate/'
  #   restart: always
  #   volumes:
  #     - './src/tasksupdate/:/project'
  #     - './src/main/:/commons'
  #     - './data:/data'
