version: '3'

services:

  www:
    hostname: www
    build: './cloud/containers/www'
    restart: always
    volumes:
      - './cloud/containers/www/html:/usr/share/nginx/html'
    ports:
      - '80:80'

  api_tasks_create:
    hostname: 'api_tasks_create'
    build: './cloud/containers/tasks-create/'
    restart: always
    volumes:
      - './cloud/containers/tasks-create/:/agenda'
      - './cloud/storage/commons/:/agenda/commons'
      - './data:/agenda/data'

  api_tasks_list:
    hostname: 'api_tasks_list'
    build: './cloud/containers/tasks-list/'
    restart: always
    volumes:
      - './cloud/containers/tasks-list/:/agenda'
      - './cloud/storage/commons/:/agenda/commons'
      - './data:/agenda/data'
